### ISSUE TITLE
KPack a few small questions

### ISSUE THREAD

**Issue by hubgogo** [bkader/Skada-WoTLK#107]
1：The avatar size will return to 100% after zooming in and moving
![2023-02-22_084033](https://user-images.githubusercontent.com/91697479/220491905-350dcbcd-a01b-45bf-8bca-6b9b921d8362.png)
![2023-02-22_105944](https://user-images.githubusercontent.com/91697479/220510242-4dc036be-b4c2-4612-a609-319ec1cee890.png)

2：The function of GearScoreLite is not perfect, the mouse pointer does not display GS, it can only be displayed on the character interface, so you can only install GearScoreLite monomer and Tooltip separately

![2023-02-23_185304](https://user-images.githubusercontent.com/91697479/220887008-4c2ff753-a037-4096-bf41-f75339b6203f.png)

![2023-02-23_185345](https://user-images.githubusercontent.com/91697479/220887021-c05f79fd-c3b2-429e-bb28-cd4fbd5941a7.png)

**The default GearScoreLite can only be displayed in the character panel**
![图片](https://user-images.githubusercontent.com/91697479/220887285-de06f108-54c3-45f4-a20c-54189c198f34.png)

These should be found by now. It still works great. thanks.

**Comment by hubgogo** [comment]
3：Can the icons in the red frame be moved to the position of the yellow frame on the mini-map?
![2023-02-23_184955](https://user-images.githubusercontent.com/91697479/220886623-cd8a4136-7dcc-4a53-b39c-501c4f504115.png)

**Comment by bkader** [comment]
@hubgogo do you realize you are on the wrong repository?
Reply before closing this irrelevant issue: I no longer do any changes to KPack, issues are closed and only pull requests can be accepted.
1. I cannot confirm nor inform portraits size resetting to 100%, it might be due to Move anything.
2. GearScoreLite was meant to be used on target and not on mouse over, switch to the original addon if you think it's better.
3. No, it was a quick minimal button grabber with no settings.
