### ISSUE TITLE
Even if you are in combat addon won't record any data

### ISSUE THREAD

**Issue by CraftedRO** [bkader/Skada-WoTLK#109]
**Describe the bug**
Skada Version: 1.8.84
Even if you engage in combat, if you don't attack target, addon won't log any record (example damage taken).

**To Reproduce**
1. Go to any aggresive creature
2. Engage in combat
3. Wait to take some damage
4. See nothing record in damage taken even if you actually take damage

**Expected behavior**
It shoud log from the first damage taken.

**Video**

https://user-images.githubusercontent.com/24683355/230639884-1e63acc9-b501-4b7b-b5df-9671ae37b0e6.mp4

**Additional context**
It is also valid for cataclism version.

**Error Log**

```

```

**Comment by bkader** [comment]
Hello @CraftedRO .. I am not sure if it's due to a bug in v1.8.84 (_if it is then sorry for the inconvenient_) but on the actual one I have (_v1.8.85_) it works fine, with or without aggressive mode enabled. You can try once it's pushed to GitHub.

https://github.com/bkader/Skada-WoTLK/assets/4732702/5891a7c6-4932-4124-81d2-6f2b9fdbced0

_Keep this issue open until you test the next push, if it works you can close it._
