### ISSUE TITLE
Arena

### ISSUE THREAD

**Issue by ujebehege** [bkader/Skada-WoTLK#13]
requests fixes for arena/ srry for english native russian speaker
1. can u do calculation of everything for the arena,  like it should show arena name not name of ppl that i dmged / total of arena idk how to say it 
2. and it doesnt show that what spell was resisted , like when i spam purge and purge will resisted it should count in addon and the end battle in arena it shows like u click into spell and ot shows how much this spell missed / dodged / parried / resisted and vs who it was resisted

**Comment by bkader** [comment]
Hi and I am sorry for my late reply.
Honestly I tried to read it many times but the only thing I could get out of it is that you want the addon to work for pvp, arenas mainly, I have never ever tested the addon in pvp because it is (_at least imo_) made for PvE.

Implementing such thing requires a bit of code rewrite, like giving the player the possiblity to select what and when to collect data, just like recount does.

As for more details about how much was resisted, absorbed, blocked...etc, I will soon implement it, I'm just working on several addons at a time so whenever I want to change a bit I switch to the next addon ^^ .. I will keep you updated.

**Comment by bkader** [comment]
I apologize, I did my best to understand the issue but I sadly couldn't. The little I understood was already fixed/added in later updates. I am closing this 8 months issue.
