### ISSUE TITLE
Current Fight and Total

### ISSUE THREAD

**Issue by Noob1e** [bkader/Skada-WoTLK#64]
If I choose "Current Fight" segment, I can see the spells and the targets. But if I choose "Total" segment, then it shows only the spells. I can't see the targets even if I shift+click on the bars.

Current
![C1](https://user-images.githubusercontent.com/27544010/131241235-543f0511-9a28-44e9-86e2-1bbddd89b46c.jpg)

Current
![C2](https://user-images.githubusercontent.com/27544010/131241236-7ae6b6e3-90fe-4acb-8a25-57ec4d92e13e.jpg)

Total
![T1](https://user-images.githubusercontent.com/27544010/131241239-d32e334a-52dd-465c-abed-fcc18b1383d2.jpg)

Total
![T2](https://user-images.githubusercontent.com/27544010/131241243-dd49e1fb-d66f-4e13-9e5c-3bab05a44468.jpg)

**Comment by bkader** [comment]
Hello @Noob1e. This is not a bug, this is intentional.

All segments store as many details as possible except for the **Total** segment, some data are only reserved for the **current** segment (_or the segment itself if you want_), if you check modules that record data only to the current segment on the default Skada, then you choose the Total segment, you can still see the tooltip but because the data is missing (_it wasn't recorded for the total segment_), the tooltip is missing and you only see `Click for ...`, if you click you will see an empty window.

This _unwanted_ behavior was fixe by adding a key that you can find in almost all modules `OnEnable` functions where modules metadata are registered, the key is called **nototalclick** that are used by the function **ignoredTotalClick** in `Skada.lua` to ignore clicks for certain submodules when it comes to the total segment. This is purely visual because even if you remove it, all modules that don't record detailed data to the total segment will show empty windows.

**Comment by Noob1e** [comment]
Alright, I see... Thanks for your answer :)
